[project]
name = "discord-leveling-bot"
version = "0.1.0"
description = "Discord bot for leveling system"
authors = [
    {name = "Hyromy", email = "formulajoel9@gmail.com"},
]
license = {text = "MIT license"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "discord-py (>=2.7.1,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning:discord.ext.commands.core",
]

[dependency-groups]
testing = [
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.2.0,<2.0.0)"
]
dev = [
    "ruff (>=0.16.7,<0.17.0)"
]
