"""init tables

Revision ID: 96d46162649a
Revises: 
Create Date: 2026-10-05 16:53:48.288367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d46162649a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('formula', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id_member', sa.BigInteger(), nullable=False),
    sa.Column('id_guild', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_guild'], ['guild.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_member'], ['member.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_member', 'id_guild')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level')
    op.drop_table('member')
    op.drop_table('guild')
    # ### end Alembic commands ###
